//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndiaHouseSalesOrder.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportPicturesChecked {
            get {
                return ((bool)(this["ExportPicturesChecked"]));
            }
            set {
                this["ExportPicturesChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\IHB-FILE\\Quickbooks Data Files\\QuickBooks India House Brass\\India House Brass, " +
            "Inc - Images\\")]
        public string ImagesLocation {
            get {
                return ((string)(this["ImagesLocation"]));
            }
            set {
                this["ImagesLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ihb-file\\IHBData\\Labels\\QuickBooks Companion Print Labels.btw")]
        public string BartenderFileLocation15x2 {
            get {
                return ((string)(this["BartenderFileLocation15x2"]));
            }
            set {
                this["BartenderFileLocation15x2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ihb-file\\IHBData\\Labels\\QuickBooks Companion Print Labels Data Source.xlsx")]
        public string ExcelDataSourceLocation {
            get {
                return ((string)(this["ExcelDataSourceLocation"]));
            }
            set {
                this["ExcelDataSourceLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<IndiaHouse.Core.Models.InventoryItem> CachedItems {
            get {
                return ((global::System.Collections.Generic.List<IndiaHouse.Core.Models.InventoryItem>)(this["CachedItems"]));
            }
            set {
                this["CachedItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ihb-file\\IHBData\\Labels\\QuickBooks Companion Print Labels 2x2.btw")]
        public string BartenderFileLocation2x2 {
            get {
                return ((string)(this["BartenderFileLocation2x2"]));
            }
            set {
                this["BartenderFileLocation2x2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ihb-file\\IHBData\\Labels\\QuickBooks Companion Print Customer Labels.btw")]
        public string CustomerLabelBartenderFileLoc {
            get {
                return ((string)(this["CustomerLabelBartenderFileLoc"]));
            }
            set {
                this["CustomerLabelBartenderFileLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\ihb-file\\IHBData\\Labels\\QuickBooks Companion Print Customer Labels Data Source." +
            "xlsx")]
        public string CustomerLabelExcelFileLoc {
            get {
                return ((string)(this["CustomerLabelExcelFileLoc"]));
            }
            set {
                this["CustomerLabelExcelFileLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<IndiaHouse.Core.Models.Customer> CachedCustomers {
            get {
                return ((global::System.Collections.Generic.List<IndiaHouse.Core.Models.Customer>)(this["CachedCustomers"]));
            }
            set {
                this["CachedCustomers"] = value;
            }
        }
    }
}
